CREATE CONSTRAINT idx1 IF NOT EXISTS ON (a:User) ASSERT a.id IS UNIQUE;
CREATE CONSTRAINT idx2 IF NOT EXISTS ON (a:Group) ASSERT a.id IS UNIQUE;
CREATE CONSTRAINT idx3 IF NOT EXISTS ON (a:Role) ASSERT a.id IS UNIQUE;
CREATE CONSTRAINT idx4 IF NOT EXISTS ON (a:Policy) ASSERT a.id IS UNIQUE;
