### SEND MESSAGE
POST localhost:8080/api/produce
Content-Type: application/json

{
  "title": "TestSend2",
  "contents": "contents"
}

### SEND MESSAGE2
POST localhost:8080/api/producer/send

### Get Message by manually
GET localhost:8080/api/consumer/consume?partition=0&offset=0
